//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Storeroom_zjo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StoreroomEntities : DbContext
    {
        public StoreroomEntities()
            : base("name=StoreroomEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customers_tbl> Customers_tbl { get; set; }
        public virtual DbSet<Parts_tbl> Parts_tbl { get; set; }
        public virtual DbSet<PartsManufacturers_tbl> PartsManufacturers_tbl { get; set; }
        public virtual DbSet<Positions_tbl> Positions_tbl { get; set; }
        public virtual DbSet<Repairs_tbl> Repairs_tbl { get; set; }
        public virtual DbSet<Users_tbl> Users_tbl { get; set; }
        public virtual DbSet<Vehicles_tbl> Vehicles_tbl { get; set; }
    }
}
