//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Storeroom_zjo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parts_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Parts_tbl()
        {
            this.Repairs_tbl = new HashSet<Repairs_tbl>();
        }
    
        public int IdPart { get; set; }
        public Nullable<int> IdManufacturer { get; set; }
        public string PartName { get; set; }
        public string ManufacturerCode { get; set; }
        public Nullable<bool> Orginal { get; set; }
        public Nullable<bool> Artificial { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> MinimalStock { get; set; }
        public Nullable<bool> AutomaticOrder { get; set; }
    
        public virtual PartsManufacturers_tbl PartsManufacturers_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Repairs_tbl> Repairs_tbl { get; set; }
    }
}
