//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Storeroom_zjo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_tbl
    {
        public int IdUser { get; set; }
        public string UserName { get; set; }
        public Nullable<int> IdPosition { get; set; }
        public string Permission { get; set; }
    
        public virtual Positions_tbl Positions_tbl { get; set; }
    }
}
